#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UsersController
    prefix: /api

#else this is route for Angular 2
fallback:
    path: /{url}
    defaults: { _controller: AppBundle:Default:index, url: null }
    requirements:
        url: ^(?!api).*
